name: baseline_ngfw_v10
label: baseline the NGFW
description: Ansible playbook to license the NGFW and apply content updates and software upgrades
type: docker
labels:
  collection: Hello World

variables:
  - name: ip_address
    description: NGFW IP Address
    default: 192.168.55.10
    type_hint: text
  #- name: TARGET_PORT
  #  description: Panorama API port
  #  default: 443
  #  type_hint: number
  #  help_text: used in cases where non-standard ports are required
  - name: username
    description: NGFW Username
    default: admin
    type_hint: text
  - name: password
    description: NGFW Password
    default:
    type_hint: password
  - name: auth_code
    description: NGFW authcode
    default: 1BADCODE
    type_hint: text
  - name: desired_version
    description: desired NGFW software version
    default: 10.0.3
    type_hint: text
  - name: force_content_update
    description: include initial content update
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'
  - name: update_av
    description: include initial antivirus update
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed

snippets:
  - name: ansible_base_image
    image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:dev
    async: True
    cmd: |
      ansible-playbook -i '../local_test_ansible/panos-ansible-upgrade-downgrade/inventory.yml'
      '../local_test_ansible/panos-ansible-upgrade-downgrade/manage_panos_software.yml' -e 'ip_address="{{ ip_address }}"'
      -e 'username="{{ username }}"' -e 'password="{{ password }}"'
      -e 'auth_code="{{ auth_code}}"' -e 'desired_version="{{ desired_version }}"'
      -e 'force_update_content="{{ force_content_update }}"' -e 'update_av="{{ update_av }}"'