- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - pan_community.skillet

  vars:
    provider:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'

  tasks:
    -
    - name: Include User Variables
      include_vars: vars/main.yml

    - name: "running test 1 playbook"
      debug:
        msg: "test 1"

    - name: Ensure deps are avabilable
      # Ensure we have all the right requirements installed in this environment
      pip:
        name:
          - pan-python
          - pandevice
          - xmltodict
          - requests
          - requests_toolbelt

    # check access to the system and pull a few values
    - name: show system info
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 10
      delay: 10

    # json to dict to use in multiple places
    - set_fact: system_info_json="{{ system_info.stdout | from_json }}"

    # output software version for min version check
    - name: software version
      debug: msg='software version is {{ system_info_json.response.result.system['sw-version'] }}'
