name: auto_deploy_configure_skillet_v10
label: Automated baseline and configure for the Hello World Solution
description: |-
  baseline and configure a 10.0 NGFW
type: python3
labels:
  collection:
    - Hello World

variables:
  - name: TARGET_IP
    description: Panorama IP
    default: 192.168.55.10
    type_hint: text
  - name: TARGET_PORT
    description: Panorama API port
    default: 443
    type_hint: number
    help_text: used in cases where non-standard ports are required
  - name: TARGET_USERNAME
    description: Panorama Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Panorama Password
    default:
    type_hint: password
  - name: auth_code
    description: NGFW authcode
    default: 1BADCODE
    type_hint: text
  - name: desired_version
    description: desired NGFW software version
    default: 10.0.3
    type_hint: text
  - name: force_content_update
    description: include initial content update
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'
  - name: update_av
    description: include initial antivirus update
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'

snippets:

  - name: autorun
    file: autorun.py

